B = set()

B.add(9)
B.add(8)
B.add(6)
B.add(77)
B.add(23)
B.add(9)
print('adding elements to B', B)

B.remove(9)
B.remove(77)
B.remove(6)
B.remove(23)
B.remove(8)
print('removing elements from B',B)

A = set()
A.add('sad')
A.add('happy')
A.add('cheerful')
A.add('dull')
A.add(10)
B.add(9)
B.add(8)
B.add(6)
B.add(77)
B.add(23)
B.add(9)
C = A.union(B)
print('union', C)

D = A.intersection(B)
print('intersection', D)

E = A.difference(B)
print('Difference', E)

A = set([2,3,4,5,6])
B = set([2,3,4,5])
print(A, B, 'is A a subset of B?', A.issubset(B))
print(A, B, 'is A a superset of B?', A.issuperset(B))

print(A, B, 'is B a subset of A?', B.issubset(A))
print(A, B, 'is B a superset of A?', B.issuperset(A))
